name: Deploy to cPanel

on:
  push:
    branches:
      - master  # Adjust as needed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare ZIP file
        run: |
          # Create a ZIP file containing the required files
          zip -r deploy.zip path/to/your/files  # Adjust this path

      - name: Upload ZIP to cPanel
        env:
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_API_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
          CPANEL_EXTRACT_DIR: "/bookmark.johnkaburu.co.ke" # Adjust this path
        run: |
          # Upload the ZIP file using cPanel API
          curl -s -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
            -F "file=@deploy.zip" \
            "https://${CPANEL_DOMAIN}:2083/execute/Fileman/upload_file?dir=${CPANEL_EXTRACT_DIR}"

          # Construct full path to ZIP file
          ZIP_FILE_PATH="${CPANEL_EXTRACT_DIR}/deploy.zip"
          echo "Checking for ZIP file at: $ZIP_FILE_PATH"

          # Check if the ZIP file exists after upload
          MAX_TRIES=10
          SLEEP_DURATION=2

          for (( i=0; i<$MAX_TRIES; i++ )); do
            FILE_CHECK=$(curl -s -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
              -d "file=$ZIP_FILE_PATH" \
              "https://${CPANEL_DOMAIN}:2083/execute/Fileman/file_exists")

            if [[ $FILE_CHECK == *'"result":1'* ]]; then
              echo "ZIP file found: $ZIP_FILE_PATH"
              break
            else
              echo "ZIP file not found, retrying... ($((i+1))/$MAX_TRIES)"
              sleep $SLEEP_DURATION
            fi
          done

          # Create PHP extraction script
          echo "<?php
          error_reporting(E_ALL);
          ini_set('display_errors', 1);

          // Set paths
          \$zipFile = '$ZIP_FILE_PATH'; // Ensure this matches your upload logic
          \$extractTo = '/home/ilqnbdpj/bookmark.johnkaburu.co.ke/extracted'; // Set your extraction directory
          \$logFile = 'debug_log.txt'; // Log file path

          // Log the start of extraction
          file_put_contents(\$logFile, \"Attempting to extract: \" . \$zipFile . PHP_EOL, FILE_APPEND);

          // Check if the ZIP file exists
          if (file_exists(\$zipFile)) {
              \$zip = new ZipArchive;
              if (\$zip->open(\$zipFile) === TRUE) {
                  // Create extraction directory if it doesn't exist
                  if (!is_dir(\$extractTo)) {
                      mkdir(\$extractTo, 0777, true);
                  }
                  // Extract the ZIP file
                  \$zip->extractTo(\$extractTo);
                  \$zip->close();
                  file_put_contents(\$logFile, \"Extraction successful to: \" . \$extractTo . PHP_EOL, FILE_APPEND);
                  echo \"Extraction successful.\";
              } else {
                  file_put_contents(\$logFile, \"Failed to open the ZIP file.\" . PHP_EOL, FILE_APPEND);
                  echo \"Failed to open the ZIP file.\";
              }
          } else {
              file_put_contents(\$logFile, \"Zip file does not exist: \" . \$zipFile . PHP_EOL, FILE_APPEND);
              echo \"Zip file does not exist. Please ensure the file was uploaded successfully.\";
          }
          ?>" > extract.php

          # Upload the extraction script
          curl -s -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
            -F "file=@extract.php" \
            "https://${CPANEL_DOMAIN}:2083/execute/Fileman/upload_file?dir=${CPANEL_EXTRACT_DIR}"

          # Run the extraction script
          curl -s -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
            "https://${CPANEL_DOMAIN}:2083/execute/PhpMyAdmin/execute?file=extract.php"
