name: Deploy to cPanel via File Upload with SFTP Extraction
on:
  push:
    branches: [master]  # Change to your default branch name if different
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Create a zip from the dist directory with explicit path handling
      - name: Create deployment package
        run: |
          timestamp=$(date +%s)
          DEPLOY_ZIP="deploy_${timestamp}.zip"
          echo "DEPLOY_ZIP=$DEPLOY_ZIP" >> $GITHUB_ENV
          cd dist && zip -r "$GITHUB_WORKSPACE/$DEPLOY_ZIP" . && cd ..
          echo "Created zip file: $GITHUB_WORKSPACE/$DEPLOY_ZIP"
          ls -la "$GITHUB_WORKSPACE"  # List files in workspace to verify zip creation
      - name: Upload and extract to cPanel via SFTP
        env:
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
          CPANEL_EXTRACT_DIR: /bookmark.johnkaburu.co.ke  # Change this to the desired cPanel directory
        run: |
          echo "Using CPANEL_DOMAIN: $CPANEL_DOMAIN"
          echo "Uploading and extracting to CPANEL_EXTRACT_DIR: $CPANEL_EXTRACT_DIR"
          
          # Check if the zip file exists
          if [ ! -f "$GITHUB_WORKSPACE/$DEPLOY_ZIP" ]; then
            echo "Error: Zip file $DEPLOY_ZIP not found."
            exit 1
          fi
          
          # Upload the zip file using SFTP
          echo "Uploading the zip file using SFTP..."
          sftp -o StrictHostKeyChecking=no $CPANEL_USERNAME@$CPANEL_DOMAIN <<EOF
          put $GITHUB_WORKSPACE/$DEPLOY_ZIP $CPANEL_EXTRACT_DIR/$DEPLOY_ZIP
          EOF
          
          # Extract the zip file using SFTP
          echo "Extracting the zip file using SFTP..."
          sftp -o StrictHostKeyChecking=no $CPANEL_USERNAME@$CPANEL_DOMAIN <<EOF
          cd $CPANEL_EXTRACT_DIR
          unzip -o $DEPLOY_ZIP
          EOF
          
          # Cleanup the deployment zip file
          echo "Cleaning up the deployment zip file..."
          sftp -o StrictHostKeyChecking=no $CPANEL_USERNAME@$CPANEL_DOMAIN <<EOF
          rm $CPANEL_EXTRACT_DIR/$DEPLOY_ZIP
          EOF
      - name: Verify deployment
        if: success()
        run: |
          echo "Deployment completed successfully"
          echo "Timestamp: $(date)"
      - name: Handle failure
        if: failure()
        run: |
          echo "Deployment failed"
          echo "Contents of current directory:"
          ls -la
