name: Deploy to cPanel via File Upload
on:
  push:
    branches: [ master ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Creating zip from dist directory with explicit path handling
      - name: Create deployment package
        run: |
          timestamp=$(date +%s)
          DEPLOY_ZIP="deploy_${timestamp}.zip"
          echo "DEPLOY_ZIP=$DEPLOY_ZIP" >> $GITHUB_ENV
          cd dist && zip -r "$GITHUB_WORKSPACE/$DEPLOY_ZIP" . && cd ..
          ls -la "$GITHUB_WORKSPACE"  # Debug: list files in workspace to verify zip creation

      - name: Upload and deploy
        run: |
          # Debug: Print file existence
          echo "Checking for zip file: $DEPLOY_ZIP"
          ls -la "$GITHUB_WORKSPACE/$DEPLOY_ZIP"
          
          # Upload new files with explicit file path
          curl -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
               -F "dir=/public_html" \
               -F "file=@$GITHUB_WORKSPACE/$DEPLOY_ZIP" \
               "https://${{ secrets.CPANEL_DOMAIN }}:2083/execute/Fileman/upload_files"
          
          if [ $? -eq 0 ]; then
            echo "Upload successful"
          else
            echo "Upload failed"
            exit 1
          fi

          # Extract with overwrite
          curl -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
               -d "dir=/public_html" \
               -d "file=$DEPLOY_ZIP" \
               -d "overwrite=1" \
               "https://${{ secrets.CPANEL_DOMAIN }}:2083/execute/Fileman/extract_files"

          # Cleanup deployment zip
          curl -H "Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}" \
               -d "dir=/public_html" \
               -d "file=$DEPLOY_ZIP" \
               "https://${{ secrets.CPANEL_DOMAIN }}:2083/execute/Fileman/delete_file"

      - name: Verify deployment
        if: success()
        run: |
          echo "Deployment completed successfully"
          echo "Timestamp: $(date)"
          
      - name: Handle failure
        if: failure()
        run: |
          echo "Deployment failed"
          echo "Contents of current directory:"
          ls -la
