name: Deploy to cPanel via File Upload with Manual Extract
on:
  push:
    branches: [master]  # Change to your default branch name if different
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Create a zip from the dist directory with explicit path handling
      - name: Create deployment package
        run: |
          timestamp=$(date +%s)
          DEPLOY_ZIP="deploy_${timestamp}.zip"
          echo "DEPLOY_ZIP=$DEPLOY_ZIP" >> $GITHUB_ENV
          cd dist && zip -r "$GITHUB_WORKSPACE/$DEPLOY_ZIP" . && cd ..
          echo "Created zip file: $GITHUB_WORKSPACE/$DEPLOY_ZIP"
          ls -la "$GITHUB_WORKSPACE"  # List files in workspace to verify zip creation
      - name: Upload to cPanel
        env:
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_API_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
          CPANEL_EXTRACT_DIR: /bookmark.johnkaburu.co.ke  # Change this to the desired cPanel directory
        run: |
          echo "Using CPANEL_DOMAIN: $CPANEL_DOMAIN"
          echo "Uploading to CPANEL_EXTRACT_DIR: $CPANEL_EXTRACT_DIR"
          
          # Check if the zip file exists
          if [ ! -f "$GITHUB_WORKSPACE/$DEPLOY_ZIP" ]; then
            echo "Error: Zip file $DEPLOY_ZIP not found."
            exit 1
          fi
          
          # Upload the zip file
          UPLOAD_URL="https://$CPANEL_DOMAIN:2083/execute/Fileman/upload_files"
          echo "Upload URL: $UPLOAD_URL"
          
          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -F "dir=$CPANEL_EXTRACT_DIR" \
               -F "file=@$GITHUB_WORKSPACE/$DEPLOY_ZIP" \
               "$UPLOAD_URL" || { echo "Upload failed"; exit 1; }
      - name: Extract on cPanel
        env:
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_API_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
          CPANEL_EXTRACT_DIR: /bookmark.johnkaburu.co.ke  # Change this to the desired cPanel directory
        run: |
          echo "Extracting ZIP file in CPANEL_EXTRACT_DIR: $CPANEL_EXTRACT_DIR"
          
          # List files in the directory to verify upload
          LIST_URL="https://$CPANEL_DOMAIN:2083/execute/Fileman/list_files"
          echo "Listing files in directory after upload:"
          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -d "dir=$CPANEL_EXTRACT_DIR" \
               "$LIST_URL"
          
          # Extract the zip file manually
          echo "Extracting the zip file manually..."
          EXTRACT_COMMAND="unzip -o $CPANEL_EXTRACT_DIR/$(basename $DEPLOY_ZIP) -d $CPANEL_EXTRACT_DIR"
          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -d "cmd=$EXTRACT_COMMAND" \
               "https://$CPANEL_DOMAIN:2083/execute/ShellExec/exec_for_pkg"
      - name: Verify deployment
        if: success()
        run: |
          echo "Deployment completed successfully"
          echo "Timestamp: $(date)"
      - name: Handle failure
        if: failure()
        run: |
          echo "Deployment failed"
          echo "Contents of current directory:"
          ls -la
