name: Deploy to cPanel via File Upload

on:
  push:
    branches: [master]  # Change to your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create a zip from the dist directory with explicit path handling
      - name: Create deployment package
        run: |
          timestamp=$(date +%s)
          DEPLOY_ZIP="deploy_${timestamp}.zip"
          echo "DEPLOY_ZIP=$DEPLOY_ZIP" >> $GITHUB_ENV
          cd dist && zip -r "$GITHUB_WORKSPACE/$DEPLOY_ZIP" . && cd ..
          echo "Created zip file: $GITHUB_WORKSPACE/$DEPLOY_ZIP"
          ls -la "$GITHUB_WORKSPACE"  # List files in workspace to verify zip creation

      - name: Upload and deploy to cPanel
        env:
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_API_TOKEN: ${{ secrets.CPANEL_API_TOKEN }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
        run: |
          echo "Using CPANEL_DOMAIN: $CPANEL_DOMAIN"

          # Check if the zip file exists
          if [ ! -f "$GITHUB_WORKSPACE/$DEPLOY_ZIP" ]; then
            echo "Error: Zip file $DEPLOY_ZIP not found."
            exit 1
          fi

          # Upload the zip file
          UPLOAD_URL="https://$CPANEL_DOMAIN:2083/execute/Fileman/upload_files"
          echo "Upload URL: $UPLOAD_URL"
          
          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -F "dir=/bookmark.johnkaburu.co.ke" \
               -F "file=@$GITHUB_WORKSPACE/$DEPLOY_ZIP" \
               "$UPLOAD_URL" || { echo "Upload failed"; exit 1; }

          # List files in the directory to verify upload
          LIST_URL="https://$CPANEL_DOMAIN:2083/execute/Fileman/list_files"
          echo "Listing files in directory after upload:"
          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -d "dir=/bookmark.johnkaburu.co.ke" \
               "$LIST_URL"

          # Extract the zip file with overwrite option
          EXTRACT_URL="https://$CPANEL_DOMAIN:2083/execute/Fileman/extract_files"
          echo "Extract URL: $EXTRACT_URL"

          # Verbose curl command for extracting the zip file
          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -d "dir=/bookmark.johnkaburu.co.ke" \
               -d "file=$(basename $DEPLOY_ZIP)" \
               -d "overwrite=1" \
               "$EXTRACT_URL" -v || { echo "Extraction failed"; exit 1; }

          # Cleanup deployment zip file
          CLEANUP_URL="https://$CPANEL_DOMAIN:2083/execute/Fileman/delete_file"
          echo "Cleanup URL: $CLEANUP_URL"

          curl -H "Authorization: cpanel ${CPANEL_USERNAME}:${CPANEL_API_TOKEN}" \
               -d "dir=/bookmark.johnkaburu.co.ke" \
               -d "file=$(basename $DEPLOY_ZIP)" \
               "$CLEANUP_URL" || { echo "Cleanup failed"; exit 1; }

      - name: Verify deployment
        if: success()
        run: |
          echo "Deployment completed successfully"
          echo "Timestamp: $(date)"

      - name: Handle failure
        if: failure()
        run: |
          echo "Deployment failed"
          echo "Contents of current directory:"
          ls -la
